### ISSUE TITLE
No internal MAG sensor?

### ISSUE THREAD

**Issue by napdynamite** [NXPHoverGames/NXP-FMUMRT#1]
Hi,

I have been trying to find the internal MAG sensor on FMURT6 BOM but I guess this design does not have internal MAG sensor. Or is the design pending?

**Comment by igalloway** [comment]
This is a PX4 FMUM (module) design. There is an IMU module that attaches on a flex cable. Also there is/may be one on a carrier board. 
I suggest you look at the RT1176 designs instead. We are manufacturing that and it is validation testing.
There will also be a simpler RT1060 design available shortly.
You may email me directly for more detailed discussion about your needs:
iain.galloway@nxp.com
