### ISSUE TITLE
FMUM-RT117X SuperCap

### ISSUE THREAD

**Issue by napdynamite** [NXPHoverGames/NXP-FMUMRT#2]
Hi,

There's a supercap used in the FMUM for power backup. In my understanding, this is used in the event when 3V3 VDD is no longer there and supercap may provide power for sometime, right?

This supercap is no longer available and is obsolete. What would happen if this supercap is eliminated altogether? Atleast for lab/ground verifications where we make sure FMU_VDD is constant and good.

**Comment by igalloway** [comment]
We are aware that this supercap is no longer available officially. (there is stock in the market)
We have adjusted the production design to include a lower capacity alternative supercap that is available
We also allowed for a primary small lithium cell on the carrier board.

The actual usage and need is up to the application.
the primary goal is to keep a real time clock and some other log data available in volatile memory when there may be a shutdown/battery swap or other event.
Typically software will regain the Real time clock from something like a GPS. But it could of course come from another source.

My *personal opinion* is that a primary lithium cell on the carrier board is the lowest cost and best performing option in many cases.


Regards
-iain

Iain Galloway
NXP Semiconductors
Mobile Robotics Domain Lead, Drones and Rovers
System Innovations CTO R&D
TX30/MS:OE320, Office F3-149
6501 W William Cannon Dr
Austin, TX, USA 78735

978-494-4246


From: Anas Bin Iftikhar ***@***.***>
Sent: Thursday, June 6, 2024 3:34 AM
To: NXPHoverGames/NXP-FMUMRT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [NXPHoverGames/NXP-FMUMRT] FMUM-RT117X SuperCap (Issue #2)

Caution: This is an external email. Please take care when clicking links or opening attachments. When in doubt, report the message using the 'Report this email' button


Hi,

There's a supercap used in the FMUM for power backup. In my understanding, this is used in the event when 3V3 VDD is no longer there and supercap may provide power for sometime, right?

This supercap is no longer available and is obsolete. What would happen if this supercap is eliminated altogether? Atleast for lab/ground verifications where we make sure FMU_VDD is constant and good.

-

**Comment by napdynamite** [comment]
Thanks. 

Could you point out the small lithium cell on carrier board? I can see V_RTC_BAT nets on both FMUM PAB header and carrier board header which means some power is also coming from carrier board to RTC. But I cannot find the lithium cell or any cell holder.

**Comment by igalloway** [comment]
Right-
This is only updated on the schematics we are preparing for production.
Please standby, I will see if I can share at least this part.

On Jun 6, 2024 10:49 AM, Anas Bin Iftikhar ***@***.***> wrote:
Caution: This is an external email. Please take care when clicking links or opening attachments. When in doubt, report the message using the 'Report this email' button


Thanks.

Could you point out the small lithium cell on carrier board? I can see V_RTC_BAT nets on both FMUM PAB header and carrier board header which means some power is also coming from carrier board to RTC. But I cannot find the lithium cell or any cell holder.

**Comment by napdynamite** [comment]
Any luck on this one?

**Comment by igalloway** [comment]
Attached is the last IMU sent for schematic update.
I don't have the resulting file back yet.

Please read the notes carefully.
As mentioned there needs to be a small voltage regulator attached if one of the components is used.

Otherwise these are a copy of the PX4 IMU reference design.


Iain Galloway
NXP Semiconductors
Mobile Robotics Program Lead
6501 W William Cannon Drive
Austin, TX, USA, 78735
978-494-4246

________________________________
From: Anas Bin Iftikhar ***@***.***>
Sent: Friday, June 7, 2024 7:51:11 AM
To: NXPHoverGames/NXP-FMUMRT ***@***.***>
Cc: Iain Galloway ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [NXPHoverGames/NXP-FMUMRT] FMUM-RT117X SuperCap (Issue #2)

Caution: This is an external email. Please take care when clicking links or opening attachments. When in doubt, report the message using the 'Report this email' button


Any luck on this one?

**Comment by napdynamite** [comment]
I am talking about the lithium cell for RTB BAT that is used in carrier board as you have mentioned.

**Comment by igalloway** [comment]
Ok will need to be Monday.
Attached is a clip of how it was added to the schematic.
It's under review still.


Iain Galloway
NXP Semiconductors
Mobile Robotics Program Lead
6501 W William Cannon Drive
Austin, TX, USA, 78735
978-494-4246
________________________________
From: Anas Bin Iftikhar ***@***.***>
Sent: Friday, June 7, 2024 10:36:17 AM
To: NXPHoverGames/NXP-FMUMRT ***@***.***>
Cc: Iain Galloway ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [NXPHoverGames/NXP-FMUMRT] FMUM-RT117X SuperCap (Issue #2)

Caution: This is an external email. Please take care when clicking links or opening attachments. When in doubt, report the message using the 'Report this email' button


I am talking about the lithium cell for RTB BAT that is used in carrier board as you have mentioned.

**Comment by Taskeenriaz** [comment]
In the reference file we have BMI088, so there is a note that INT2 and INT4 are not connected as per data sheet but , in datasheet it uses, also do its specific role of accelerometer and gyro so do let me know that if we are using so what will be the  consequences.

**Comment by igalloway** [comment]
Latest design files are updated and in the directory here:
https://github.com/NXPHoverGames/NXP-FMUMRT/tree/main/FMUM-RT117x-01%20Design%20Files(2)

This version includes provisions for different (available) B1 lithium battery  or B2+B3 small supercaps in parallel as well as a battery on the Vxx Baseboard. So all options are covered.

**Comment by igalloway** [comment]
Note the IMU on flex that attaches to the FMUM is not included in the design files here yet. This is identical to the Pixhawk reference and that can be used. We will eventually duplicate it here, but that is pending.
